FROM python:3.13-alpine

WORKDIR /app

COPY shared /app/shared
COPY tier2-business/business_service.py .
COPY tier2-business/requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 5001
CMD ["python", "business_service.py"]