FROM python:3.13-alpine

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY shared /app/shared
COPY workers/order_worker.py .
COPY workers/requirements.txt .

RUN pip install -r requirements.txt
CMD ["python", "order_worker.py"]