FROM python:3.13-alpine

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

COPY shared /app/shared
COPY publisher/event_publisher.py .
COPY publisher/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "event_publisher.py"]