FROM python:3.11-alpine

WORKDIR /app
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
COPY services/payment-service/ .
COPY shared/ ./shared
RUN pip install -r requirements.txt --no-cache-dir

EXPOSE 5004
CMD ["python", "app.py"]