FROM python:3.11-alpine

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

COPY services/user-service/ .
COPY shared/ ./shared
RUN pip install -r requirements.txt --no-cache-dir

EXPOSE 5001
CMD ["python", "app.py"]